import {useState} from 'react';
import {dateFmt,money,type Expense} from '../lib/api';
import {useI18n} from '../i18n';
import {dayKey,asDate} from '../lib/contracts';
export default function ContractWizard({expense,draft,onSave,onBack}:{expense:Expense;draft:any;onSave:(d:any)=>Promise<void>;onBack:()=>void}){
 const{language,t}=useI18n();const de=language==='de';const L=(a:string,b:string)=>de?a:b;
 const[d,setD]=useState({...draft,contract_effective_from:draft.contract_effective_from||dayKey(new Date()),price_effective_from:draft.price_effective_from||draft.contract_effective_from||dayKey(new Date())});const[termMode,setTermMode]=useState(draft.contract_end!==expense.contract_end||draft.minimum_term_months!==expense.minimum_term_months?'change':'keep');const[mode,setMode]=useState(draft.cancellation_notice_days!=null?'notice':'date');const[error,setError]=useState('');const[busy,setBusy]=useState(false);
 const set=(key:string,value:any)=>setD((p:any)=>({...p,[key]:value}));
 const cancellation=()=>{if(mode==='notice'&&d.contract_end&&d.cancellation_notice_days!=null){const when=asDate(d.contract_end);when.setDate(when.getDate()-Number(d.cancellation_notice_days));return dayKey(when)}return d.cancellation_date||null};
 const fields:[string,string][]=[['name',L('Name','Name')],['entry_type',L('Eintragsart','Entry type')],['currency',L('Währung','Currency')],['amount',L('Preis','Price')],['billing_interval',L('Zahlungsintervall','Billing interval')],['contract_end',L('Vertragsende','Contract end')],['account_id',L('Konto','Account')],['category_id',L('Rubrik','Category')],['contract_holder',L('Vertragsinhaber','Contract holder')],['provider',L('Anbieter','Provider')],['status','Status'],['auto_renew',L('Automatische Verlängerung','Automatic renewal')],['cancellation_notice_days',L('Kündigungsfrist (Tage)','Notice (days)')]];
 const display=(row:any,k:string)=>k==='amount'?money(Number(row.amount),row.currency):k==='account_id'?row.account_label||row.account||'–':k==='category_id'?row.category_label||row.category||'–':k==='contract_end'?dateFmt(row.contract_end):k==='status'?t(`form.${row.status}`):k==='billing_interval'?t(`interval.${row.billing_interval}`):k==='entry_type'?t(`type.${row.entry_type}`):typeof row[k]==='boolean'?(row[k]?L('Ja','Yes'):L('Nein','No')):String(row[k]??'–');
 return <form className="entry-form contract-wizard" onSubmit={async e=>{e.preventDefault();setError('');setBusy(true);try{await onSave({...d,cancellation_date:cancellation(),cancellation_notice_days:mode==='notice'?d.cancellation_notice_days:null,renewal_period_months:d.auto_renew?Number(d.renewal_period_months||12):d.renewal_period_months,renewal_amount:d.renewal_amount?Number(d.renewal_amount):null})}catch(x:any){setError(x.message)}finally{setBusy(false)}}}>
 <div className="wizard-intro"><span className="pill">{L('Vertragsänderung prüfen','Review contract change')}</span><h2>{expense.name}</h2><p>{L('Vergangene Preise und Zuordnungen bleiben erhalten. Lege fest, wann die neuen Angaben gelten.','Previous prices and assignments are retained. Choose when the new terms take effect.')}</p></div>
 <div className="contract-diff">{fields.filter(([k])=>String((expense as any)[k]??'')!==String(d[k]??'')).map(([k,label])=><div key={k}><span>{label}</span><strong>{display(expense,k)} → {display(d,k)}</strong></div>)}</div>
 <div className="form-grid"><label>{L('Vertragsangaben gelten ab','Contract terms effective from')}<input required type="date" min={expense.history_from||undefined} value={d.contract_effective_from} onChange={e=>set('contract_effective_from',e.target.value)}/><small>{L('Auch Konto, Rubrik und Vertragsinhaber gelten ab diesem Datum.','Account, category and holder also change on this date.')}</small></label><label>{L('Neuer Preis gilt ab','New price effective from')}<input disabled={!d.update_price} required type="date" min={expense.history_from||undefined} value={d.price_effective_from} onChange={e=>set('price_effective_from',e.target.value)}/>{!d.update_price&&<small>{L('Preis unverändert; bestehende Preisplanung bleibt erhalten.','Price unchanged; existing price plans remain.')}</small>}</label>
 <label>{L('Auswirkung auf die Laufzeit','Effect on term')}<select value={termMode} onChange={e=>{const value=e.target.value;setTermMode(value);if(value==='keep')setD((p:any)=>({...p,contract_end:expense.contract_end,minimum_term_months:expense.minimum_term_months}));if(value==='open')setD((p:any)=>({...p,contract_end:null,minimum_term_months:null,auto_renew:false}))}}><option value="keep">{L('Bisherige Laufzeit behalten','Keep current term')}</option><option value="change">{L('Neue Laufzeit festlegen','Set a new term')}</option><option value="open">{L('Unbefristet weiterführen','Continue open-ended')}</option></select></label><div/>
 <label>{L('Neues Vertragsende (leer = unbefristet)','New contract end (blank = open-ended)')}<input disabled={termMode!=='change'} type="date" min={d.start_date||undefined} value={d.contract_end||''} onChange={e=>set('contract_end',e.target.value||null)}/></label><label>{L('Mindestlaufzeit in Monaten','Minimum term in months')}<input disabled={termMode!=='change'} type="number" min="1" value={d.minimum_term_months||''} onChange={e=>set('minimum_term_months',e.target.value?Number(e.target.value):null)}/></label>
 <label>{L('Kündigungsregel','Cancellation rule')}<select value={mode} onChange={e=>setMode(e.target.value)}><option value="notice">{L('Frist vor Vertragsende','Notice before contract end')}</option><option value="date">{L('Festes Kündigungsdatum / keine Angabe','Fixed deadline / unspecified')}</option></select></label>{mode==='notice'?<label>{L('Kündigungsfrist in Tagen','Notice in days')}<input type="number" min="0" value={d.cancellation_notice_days??''} onChange={e=>set('cancellation_notice_days',e.target.value===''?null:Number(e.target.value))}/><small>{L('Berechnetes Kündigungsdatum: ','Calculated deadline: ')}{dateFmt(cancellation())}</small></label>:<label>{L('Kündigungsdatum','Cancellation deadline')}<input type="date" value={d.cancellation_date||''} onChange={e=>set('cancellation_date',e.target.value||null)}/></label>}
 <label className="check"><input type="checkbox" checked={!!d.auto_renew} onChange={e=>set('auto_renew',e.target.checked)}/>{L('Automatische Vertragsverlängerung','Automatic renewal')}</label><div/>{d.auto_renew&&<><label>{L('Verlängerung um Monate','Renewal period in months')}<input required min="1" type="number" value={d.renewal_period_months||12} onChange={e=>set('renewal_period_months',Number(e.target.value))}/></label><label>{L('Preis je Zahlungsintervall ab Verlängerung','Price per billing interval after renewal')}<input min="0.01" step="0.01" type="number" value={d.renewal_amount||''} placeholder={String(d.amount)} onChange={e=>set('renewal_amount',e.target.value?Number(e.target.value):null)}/><small>{L('Leer = bisherigen Preis weiterführen. Ein ausdrücklich später geplanter Preis hat Vorrang.','Blank retains the price. An explicitly scheduled later price takes precedence.')}</small></label></>}
 </div>
 {expense.contract_versions?.some(v=>v.effective_from===d.contract_effective_from)&&<p className="form-warning">{L('An diesem Datum existiert bereits ein Vertragsstand. Er wird durch diese Angaben ersetzt.','A contract version already exists on this date. It will be replaced by these terms.')}</p>}
 <p className="settings-hint">{L('Ein zurückliegendes Datum korrigiert die Historie ab diesem Datum. Zukünftige Änderungen werden als geplant angezeigt.','A past date corrects history from that date. Future changes are shown as planned.')}</p>
 {error&&<div className="error" role="alert">{error}</div>}<div className="form-actions"><button type="button" className="secondary" disabled={busy} onClick={onBack}>{L('Zurück','Back')}</button><button disabled={busy}>{busy?'…':L('Änderung speichern','Save change')}</button></div></form>
}
