import{useState}from'react';import type{Account,Category,Expense}from'../lib/api';import{money,dateFmt}from'../lib/api';
const today=()=>new Date().toISOString().slice(0,10);
const blank={name:'',provider:'',amount:0,currency:'EUR',billing_interval:'monthly',interval_months:1,category_id:null,account_id:null,start_date:null,next_due_date:null,contract_end:null,cancellation_date:null,minimum_term_months:null,renewal_period_months:null,cancellation_notice_days:null,auto_renew:false,status:'active',essential:false,tags:'',notes:'',price_effective_from:null}
export default function ExpenseForm({expense,accounts,categories,onSave,onCancel}:{expense?:Expense;accounts:Account[];categories:Category[];onSave:(x:any)=>Promise<void>;onCancel:()=>void}){
 const[e,setE]=useState<any>(expense?{...expense,price_effective_from:today()}:blank);const[busy,setBusy]=useState(false);const set=(k:string,v:any)=>setE((p:any)=>({...p,[k]:v}));
 const interval=(v:string)=>{const m:{[k:string]:number}={monthly:1,quarterly:3,halfyearly:6,yearly:12};setE((p:any)=>({...p,billing_interval:v,interval_months:m[v]||p.interval_months||1}))}
 return <form className="form-grid" onSubmit={async ev=>{ev.preventDefault();setBusy(true);try{const payload={...e,amount:Number(e.amount),interval_months:Number(e.interval_months||1),category_id:e.category_id?Number(e.category_id):null,account_id:e.account_id?Number(e.account_id):null,minimum_term_months:e.minimum_term_months?Number(e.minimum_term_months):null,renewal_period_months:e.renewal_period_months?Number(e.renewal_period_months):null,cancellation_notice_days:e.cancellation_notice_days!==null&&e.cancellation_notice_days!==''?Number(e.cancellation_notice_days):null};delete payload.id;delete payload.monthly_equivalent;delete payload.yearly_equivalent;delete payload.category;delete payload.account;delete payload.price_history;delete payload.next_price_change;delete payload.effective_contract_end;delete payload.effective_cancellation_date;await onSave(payload)}finally{setBusy(false)}}}>
  <label className="span2">Name<input required value={e.name} onChange={x=>set('name',x.target.value)} placeholder="z. B. ChatGPT Plus"/></label>
  <label>Anbieter<input value={e.provider} onChange={x=>set('provider',x.target.value)} placeholder="OpenAI"/></label>
  <label>Betrag (€)<input required type="number" min="0.01" step="0.01" value={e.amount||''} onChange={x=>set('amount',x.target.value)}/></label>
  {expense&&<><label>Neuer Preis gültig ab<input type="date" value={e.price_effective_from||today()} onChange={x=>set('price_effective_from',x.target.value||today())}/><small>Nur relevant, wenn du den Betrag änderst. Alte Zeiträume bleiben unverändert.</small></label><div className="price-history span2"><strong>Preisverlauf</strong>{(expense.price_history||[]).map(p=><div key={p.id}><span>{dateFmt(p.valid_from)}{p.valid_to?` – ${dateFmt(p.valid_to)}`:' – weiter'}</span><b>{money(p.amount,expense.currency)}</b></div>)}{expense.next_price_change&&<small>Geplant: {money(expense.next_price_change.amount,expense.currency)} ab {dateFmt(expense.next_price_change.valid_from)}</small>}</div></>}
  <label>Abrechnung<select value={e.billing_interval} onChange={x=>interval(x.target.value)}><option value="monthly">Monatlich</option><option value="quarterly">Vierteljährlich</option><option value="halfyearly">Halbjährlich</option><option value="yearly">Jährlich</option><option value="custom">Individuell</option></select></label>
  {e.billing_interval==='custom'&&<label>Alle X Monate<input type="number" min="1" value={e.interval_months} onChange={x=>set('interval_months',x.target.value)}/></label>}
  <label>Kategorie<select value={e.category_id||''} onChange={x=>set('category_id',x.target.value||null)}><option value="">Ohne Kategorie</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>
  <label>Konto / Zahlungsweg<select value={e.account_id||''} onChange={x=>set('account_id',x.target.value||null)}><option value="">Nicht zugeordnet</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label>
  <label>Vertragsbeginn<input type="date" value={e.start_date||''} onChange={x=>set('start_date',x.target.value||null)}/></label>
  <label>Mindestlaufzeit (Monate)<input type="number" min="1" value={e.minimum_term_months||''} onChange={x=>set('minimum_term_months',x.target.value||null)} placeholder="z. B. 24"/><small>Wenn kein Vertragsende gesetzt ist, wird es daraus berechnet.</small></label>
  <label>Vertragsende<input type="date" value={e.contract_end||''} onChange={x=>set('contract_end',x.target.value||null)}/><small>Darf unterjährig liegen und hat Vorrang vor der Mindestlaufzeit.</small></label>
  <label>Nächste Fälligkeit<input type="date" value={e.next_due_date||''} onChange={x=>set('next_due_date',x.target.value||null)}/></label>
  <label>Kündigen bis<input type="date" value={e.cancellation_date||''} onChange={x=>set('cancellation_date',x.target.value||null)}/><small>Kann leer bleiben, wenn Vertragsende und Kündigungsfrist gesetzt sind.</small></label>
  <label>Kündigungsfrist<select value={[14,30,60,90].includes(Number(e.cancellation_notice_days))?String(e.cancellation_notice_days):(e.cancellation_notice_days===null||e.cancellation_notice_days===''?'':'custom')} onChange={x=>{const v=x.target.value;set('cancellation_notice_days',v==='custom'?(e.cancellation_notice_days||1):(v===''?null:Number(v)))}}><option value="">Keine / unbekannt</option><option value="14">14 Tage</option><option value="30">1 Monat / 30 Tage</option><option value="60">2 Monate / 60 Tage</option><option value="90">3 Monate / 90 Tage</option><option value="custom">Individuell</option></select></label>
  {e.cancellation_notice_days!==null&&e.cancellation_notice_days!==''&&![14,30,60,90].includes(Number(e.cancellation_notice_days))&&<label>Kündigungsfrist individuell (Tage)<input type="number" min="0" value={e.cancellation_notice_days??''} onChange={x=>set('cancellation_notice_days',x.target.value||null)}/></label>}
  <label>Status<select value={e.status} onChange={x=>set('status',x.target.value)}><option value="active">Aktiv</option><option value="paused">Pausiert</option><option value="cancelled">Gekündigt</option><option value="ended">Beendet</option></select></label>
  <label className="check"><input type="checkbox" checked={e.auto_renew} onChange={x=>set('auto_renew',x.target.checked)}/> Automatische Verlängerung</label>
  {e.auto_renew&&<label>Verlängerung um (Monate)<input type="number" min="1" value={e.renewal_period_months||''} onChange={x=>set('renewal_period_months',x.target.value||null)} placeholder="z. B. 12"/></label>}
  <label className="check"><input type="checkbox" checked={e.essential} onChange={x=>set('essential',x.target.checked)}/> Essenziell / kaum einsparbar</label>
  <label className="span2">Tags<input value={e.tags} onChange={x=>set('tags',x.target.value)} placeholder="Streaming, Arbeit, Familie"/></label>
  <label className="span2">Notizen<textarea rows={3} value={e.notes} onChange={x=>set('notes',x.target.value)} placeholder="Tarif, Ansprechpartner, Besonderheiten …"/></label>
  <div className="form-actions span2"><button type="button" className="secondary" onClick={onCancel}>Abbrechen</button><button disabled={busy}>{busy?'Speichern …':'Speichern'}</button></div>
 </form>
}
