import{useEffect,useState}from'react';
import type{Account,Category,Expense}from'../lib/api';
import{api,money,dateFmt}from'../lib/api';
import{useI18n}from'../i18n';
const today=()=>new Date().toISOString().slice(0,10);
const blank={name:'',provider:'',entry_type:'expense',amount:0,currency:'EUR',billing_interval:'monthly',interval_months:1,category_id:null,account_id:null,start_date:null,next_due_date:null,contract_end:null,cancellation_date:null,minimum_term_months:null,renewal_period_months:null,cancellation_notice_days:null,auto_renew:false,status:'active',essential:false,tags:'',notes:'',price_effective_from:null};
export default function ExpenseForm({expense,accounts,categories,onSave,onCancel,isClone=false,canAddCategory=false,onCategoryAdded}:{expense?:Expense;accounts:Account[];categories:Category[];onSave:(x:any)=>Promise<void>;onCancel:()=>void;isClone?:boolean;canAddCategory?:boolean;onCategoryAdded?:()=>Promise<void>|void}){
 const{t}=useI18n();
 const[e,setE]=useState<any>(expense?{...expense,price_effective_from:today()}:blank);const[busy,setBusy]=useState(false);const[localCategories,setLocalCategories]=useState(categories);const[addingCategory,setAddingCategory]=useState(false);const[newCategory,setNewCategory]=useState('');const[categoryBusy,setCategoryBusy]=useState(false);const[categoryError,setCategoryError]=useState('');
 useEffect(()=>setLocalCategories(categories),[categories]);
 const set=(k:string,v:any)=>setE((p:any)=>({...p,[k]:v}));
 const categoryOptions=expense?.category_id&&!localCategories.some(c=>c.id===expense.category_id)?[{id:expense.category_id,name:`${expense.category||t('form.category')} (${t('form.hidden')})`,icon:'wallet',color:expense.category_color||'#7B8798'},...localCategories]:localCategories;
 const accountOptions=expense?.account_id&&!accounts.some(a=>a.id===expense.account_id)?[{id:expense.account_id,name:`${expense.account||t('form.account')} (${t('form.hidden')})`,kind:'bank',note:''},...accounts]:accounts;
 const interval=(v:string)=>{const m:{[k:string]:number}={monthly:1,quarterly:3,halfyearly:6,yearly:12};setE((p:any)=>({...p,billing_interval:v,interval_months:m[v]||p.interval_months||1}))};
 const addCategory=async()=>{const name=newCategory.trim();if(!name)return;setCategoryBusy(true);setCategoryError('');try{const c=await api<Category>('/api/categories',{method:'POST',body:JSON.stringify({name,icon:'wallet',color:'#5B5CF0'})});setLocalCategories(v=>[...v,c].sort((a,b)=>a.name.localeCompare(b.name)));set('category_id',c.id);setNewCategory('');setAddingCategory(false);await onCategoryAdded?.()}catch(x:any){setCategoryError(x.message)}finally{setCategoryBusy(false)}};
 return <form className="form-grid" onSubmit={async ev=>{ev.preventDefault();setBusy(true);try{const payload={...e,amount:Number(e.amount),interval_months:Number(e.interval_months||1),category_id:e.category_id?Number(e.category_id):null,account_id:e.account_id?Number(e.account_id):null,minimum_term_months:e.minimum_term_months?Number(e.minimum_term_months):null,renewal_period_months:e.renewal_period_months?Number(e.renewal_period_months):null,cancellation_notice_days:e.cancellation_notice_days!==null&&e.cancellation_notice_days!==''?Number(e.cancellation_notice_days):null};for(const k of['id','monthly_equivalent','yearly_equivalent','category','category_color','account','price_history','next_price_change','effective_contract_end','effective_cancellation_date','cancelled_on'])delete payload[k];if(isClone)payload.price_effective_from=null;await onSave(payload)}finally{setBusy(false)}}}>
  <label>{t('form.type')}<select value={e.entry_type||'expense'} onChange={x=>set('entry_type',x.target.value)}><option value="expense">{t('type.expense')}</option><option value="income">{t('type.income')}</option></select></label>
  <label>{t('form.name')}<input required value={e.name} onChange={x=>set('name',x.target.value)}/></label>
  <label>{t('form.provider')}<input value={e.provider} onChange={x=>set('provider',x.target.value)}/></label>
  <label>{t('form.amount')}<input required type="number" min="0.01" step="0.01" value={e.amount||''} onChange={x=>set('amount',x.target.value)}/></label>
  {expense&&!isClone&&<><label>{t('form.priceFrom')}<input type="date" value={e.price_effective_from||today()} onChange={x=>set('price_effective_from',x.target.value||today())}/><small>{t('form.priceHelp')}</small></label><div className="price-history span2"><strong>{t('form.priceHistory')}</strong>{(expense.price_history||[]).map(p=><div key={p.id}><span>{dateFmt(p.valid_from)}{p.valid_to?` – ${dateFmt(p.valid_to)}`:` – ${t('form.continues')}`}</span><b>{money(p.amount,expense.currency)}</b></div>)}{expense.next_price_change&&<small>{t('form.planned',{amount:money(expense.next_price_change.amount,expense.currency),date:dateFmt(expense.next_price_change.valid_from)})}</small>}</div></>}
  <label>{t('form.billing')}<select value={e.billing_interval} onChange={x=>interval(x.target.value)}><option value="monthly">{t('interval.monthly')}</option><option value="quarterly">{t('interval.quarterly')}</option><option value="halfyearly">{t('interval.halfyearly')}</option><option value="yearly">{t('interval.yearly')}</option><option value="custom">{t('interval.custom')}</option></select></label>
  {e.billing_interval==='custom'&&<label>{t('form.everyMonths')}<input type="number" min="1" value={e.interval_months} onChange={x=>set('interval_months',x.target.value)}/></label>}
  <label className="category-field">{t('form.category')}<div className="select-with-action"><select value={e.category_id||''} onChange={x=>set('category_id',x.target.value||null)}><option value="">{t('form.noCategory')}</option>{categoryOptions.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select>{canAddCategory&&<button type="button" className="inline-add" title={t('form.addCategory')} onClick={()=>setAddingCategory(v=>!v)}>+</button>}</div>{canAddCategory&&addingCategory&&<div className="inline-create"><input autoFocus value={newCategory} onChange={x=>setNewCategory(x.target.value)} placeholder={t('form.newCategory')} onKeyDown={x=>{if(x.key==='Enter'){x.preventDefault();addCategory()}if(x.key==='Escape'){setAddingCategory(false);setNewCategory('')}}}/><button type="button" disabled={categoryBusy||!newCategory.trim()} onClick={addCategory}>{categoryBusy?'…':t('create')}</button></div>}{categoryError&&<small className="form-error">{categoryError}</small>}</label>
  <label>{t('form.account')}<select value={e.account_id||''} onChange={x=>set('account_id',x.target.value||null)}><option value="">{t('form.noAccount')}</option>{accountOptions.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label>
  <label>{t('form.start')}<input type="date" value={e.start_date||''} onChange={x=>set('start_date',x.target.value||null)}/></label>
  <label>{t('form.minTerm')}<input type="number" min="1" value={e.minimum_term_months||''} onChange={x=>set('minimum_term_months',x.target.value||null)}/><small>{t('form.minTermHelp')}</small></label>
  <label>{t('form.end')}<input type="date" value={e.contract_end||''} onChange={x=>set('contract_end',x.target.value||null)}/><small>{t('form.endHelp')}</small></label>
  <label>{t('form.nextDue')}<input type="date" value={e.next_due_date||''} onChange={x=>set('next_due_date',x.target.value||null)}/></label>
  <label>{t('form.cancelBy')}<input type="date" value={e.cancellation_date||''} onChange={x=>set('cancellation_date',x.target.value||null)}/><small>{t('form.cancelHelp')}</small></label>
  <label>{t('form.notice')}<select value={[14,30,60,90].includes(Number(e.cancellation_notice_days))?String(e.cancellation_notice_days):(e.cancellation_notice_days===null||e.cancellation_notice_days===''?'':'custom')} onChange={x=>{const v=x.target.value;set('cancellation_notice_days',v==='custom'?(e.cancellation_notice_days||1):(v===''?null:Number(v)))}}><option value="">{t('form.noticeNone')}</option><option value="14">{t('form.notice14')}</option><option value="30">{t('form.notice30')}</option><option value="60">{t('form.notice60')}</option><option value="90">{t('form.notice90')}</option><option value="custom">{t('form.noticeCustom')}</option></select></label>
  {e.cancellation_notice_days!==null&&e.cancellation_notice_days!==''&&![14,30,60,90].includes(Number(e.cancellation_notice_days))&&<label>{t('form.noticeDays')}<input type="number" min="0" value={e.cancellation_notice_days??''} onChange={x=>set('cancellation_notice_days',x.target.value||null)}/></label>}
  <label>{t('form.status')}<select value={e.status} onChange={x=>set('status',x.target.value)}><option value="active">{t('form.active')}</option><option value="paused">{t('form.paused')}</option><option value="cancelled">{t('form.cancelled')}</option><option value="ended">{t('form.ended')}</option></select></label>
  <label className="check"><input type="checkbox" checked={e.auto_renew} onChange={x=>setE((p:any)=>({...p,auto_renew:x.target.checked,renewal_period_months:x.target.checked?(p.renewal_period_months||12):p.renewal_period_months}))}/>{t('form.autoRenew')}</label>
  {e.auto_renew&&<label>{t('form.renewMonths')}<input type="number" min="1" value={e.renewal_period_months||''} onChange={x=>set('renewal_period_months',x.target.value||null)}/></label>}
  <label className="check"><input type="checkbox" checked={e.essential} onChange={x=>set('essential',x.target.checked)}/>{t('form.essential')}</label>
  <label className="span2">{t('form.tags')}<input value={e.tags} onChange={x=>set('tags',x.target.value)}/></label>
  <label className="span2">{t('form.notes')}<textarea rows={3} value={e.notes} onChange={x=>set('notes',x.target.value)}/><small>{t('form.notesHelp')}</small></label>
  <div className="form-actions span2"><button type="button" className="secondary" onClick={onCancel}>{t('cancel')}</button><button disabled={busy}>{busy?t('form.saving'):t('form.save')}</button></div>
 </form>
}
