import {useEffect,useMemo,useState,type FormEvent} from 'react';
import {ChevronDown,Plus,Tag,WalletCards,CalendarClock,RotateCcw,Info,BrainCircuit} from 'lucide-react';
import type{Account,Category,Expense} from '../lib/api';
import{api,money,dateFmt}from'../lib/api';
import{useI18n}from'../i18n';
import ProviderIcon from './ProviderIcon';

const today=()=>new Date().toISOString().slice(0,10);
const blank={name:'',provider:'',entry_type:'expense',amount:0,currency:'EUR',billing_interval:'monthly',interval_months:1,category_id:null,account_id:null,start_date:null,next_due_date:null,contract_end:null,cancellation_date:null,minimum_term_months:null,renewal_period_months:null,renewal_amount:null,cancellation_notice_days:null,auto_renew:false,status:'active',essential:false,recurrence_type:'recurring',amount_estimated:false,contract_url:'',contract_reference:'',tags:'',notes:'',price_effective_from:null};

export default function ExpenseForm({expense,accounts,categories,onSave,onCancel,isClone=false,onCategoryAdded,existingExpenses=[]}:{expense?:Expense;accounts:Account[];categories:Category[];onSave:(x:any)=>Promise<void>;onCancel:()=>void;isClone?:boolean;onCategoryAdded?:()=>Promise<void>|void;existingExpenses?:Expense[]}){
 const{t}=useI18n();
 const initial=expense?{...expense,price_effective_from:null}:blank;
 const[e,setE]=useState<any>(initial);const[busy,setBusy]=useState(false);const[localCategories,setLocalCategories]=useState(categories);const[localAccounts,setLocalAccounts]=useState(accounts);const[addingCategory,setAddingCategory]=useState(false);const[newCategory,setNewCategory]=useState('');const[newColor,setNewColor]=useState('#5B5CF0');const[categoryBusy,setCategoryBusy]=useState(false);const[categoryError,setCategoryError]=useState('');const[addingAccount,setAddingAccount]=useState(false);const[newAccount,setNewAccount]=useState('');const[newAccountKind,setNewAccountKind]=useState('bank');const[accountBusy,setAccountBusy]=useState(false);const[accountError,setAccountError]=useState('');const[history,setHistory]=useState<any[]>([]);
 useEffect(()=>setLocalCategories(categories),[categories]);useEffect(()=>setLocalAccounts(accounts),[accounts]);useEffect(()=>{if(expense?.id&&!isClone)api<any[]>(`/api/expenses/${expense.id}/history`).then(setHistory).catch(()=>{})},[expense?.id,isClone]);
 const set=(k:string,v:any)=>setE((p:any)=>({...p,[k]:v}));
 const categoryOptions=expense?.category_id&&!localCategories.some(c=>c.id===expense.category_id)?[{id:expense.category_id,name:`${expense.category||t('form.category')} (${t('form.hidden')})`,icon:'wallet',color:expense.category_color||'#7B8798',scope:'global' as const,created_by:null,can_edit:false},...localCategories]:localCategories;
 const accountOptions=expense?.account_id&&!localAccounts.some(a=>a.id===expense.account_id)?[{id:expense.account_id,name:`${expense.account||t('form.account')} (${t('form.hidden')})`,kind:'bank',note:'',scope:'global' as const,created_by:null,can_edit:false},...localAccounts]:localAccounts;
 const interval=(v:string)=>{const m:{[k:string]:number}={monthly:1,quarterly:3,halfyearly:6,yearly:12};setE((p:any)=>({...p,billing_interval:v,interval_months:m[v]||p.interval_months||1}))};
 const addCategory=async()=>{const name=newCategory.trim();if(!name)return;setCategoryBusy(true);setCategoryError('');try{const c=await api<Category>('/api/categories',{method:'POST',body:JSON.stringify({name,icon:'wallet',color:newColor,scope:'private'})});setLocalCategories(v=>[...v,c].sort((a,b)=>a.name.localeCompare(b.name)));set('category_id',c.id);setNewCategory('');setAddingCategory(false);await onCategoryAdded?.()}catch(x:any){setCategoryError(x.message)}finally{setCategoryBusy(false)}};
 const addAccount=async()=>{const name=newAccount.trim();if(!name)return;setAccountBusy(true);setAccountError('');try{const a=await api<Account>('/api/accounts',{method:'POST',body:JSON.stringify({name,kind:newAccountKind,note:'',scope:'private'})});setLocalAccounts(v=>[...v,a].sort((a,b)=>a.name.localeCompare(b.name)));set('account_id',a.id);setNewAccount('');setNewAccountKind('bank');setAddingAccount(false);await onCategoryAdded?.()}catch(x:any){setAccountError(x.message)}finally{setAccountBusy(false)}};
 const duplicate=useMemo(()=>{const n=(e.name||'').trim().toLowerCase(),p=(e.provider||'').trim().toLowerCase();if(!n)return null;return existingExpenses.find(x=>x.id!==expense?.id&&((x.name||'').trim().toLowerCase()===n||(p&&x.provider.trim().toLowerCase()===p&&x.account_id===Number(e.account_id||0))))||null},[e.name,e.provider,e.account_id,existingExpenses,expense?.id]);
 const priceChanged=!!expense&&!isClone&&Number(e.amount||0)!==Number(expense.amount||0);
 const activePastEnd=e.status==='active'&&e.contract_end&&new Date(e.contract_end+'T12:00:00')<new Date();
 const endBeforeDue=e.contract_end&&e.next_due_date&&e.contract_end<e.next_due_date;
 const submit=async(ev:FormEvent)=>{ev.preventDefault();setBusy(true);try{const payload={...e,amount:Number(e.amount),interval_months:Number(e.interval_months||1),category_id:e.category_id?Number(e.category_id):null,account_id:e.account_id?Number(e.account_id):null,minimum_term_months:e.minimum_term_months?Number(e.minimum_term_months):null,renewal_period_months:e.renewal_period_months?Number(e.renewal_period_months):null,renewal_amount:e.renewal_amount?Number(e.renewal_amount):null,cancellation_notice_days:e.cancellation_notice_days!==null&&e.cancellation_notice_days!==''?Number(e.cancellation_notice_days):null,price_effective_from:priceChanged?(e.price_effective_from||today()):null};for(const k of['id','monthly_equivalent','yearly_equivalent','category','category_color','account','price_history','next_price_change','effective_contract_end','effective_cancellation_date','cancelled_on'])delete payload[k];if(isClone)payload.price_effective_from=null;await onSave(payload)}finally{setBusy(false)}};
 return <form className="entry-form" onSubmit={submit}>
  {duplicate&&<div className="duplicate-warning"><strong>⚠ {t('form.duplicateTitle')}</strong><span>{t('form.duplicateHelp',{name:duplicate.name})}</span></div>}
  <section className="entry-core form-grid">
    <label>{t('form.type')}<select value={e.entry_type||'expense'} onChange={x=>set('entry_type',x.target.value)}><option value="expense">{t('type.expense')}</option><option value="income">{t('type.income')}</option></select></label>
    <label>{t('form.name')}<input required value={e.name} onChange={x=>set('name',x.target.value)}/></label>
    <label>{t('form.provider')}<div className="provider-input"><ProviderIcon provider={e.provider} name={e.name} size={34}/><input value={e.provider} onChange={x=>set('provider',x.target.value)} placeholder={t('form.providerPlaceholder')}/></div></label>
    <label>{t('form.amount')}<div className="amount-row"><input required type="number" min="0.01" step="0.01" value={e.amount||''} onChange={x=>set('amount',x.target.value)}/><label className="mini-check"><input type="checkbox" checked={!!e.amount_estimated} onChange={x=>set('amount_estimated',x.target.checked)}/>{t('form.estimatedVariable')}</label></div>{e.amount_estimated&&<small>{t('form.estimatedHelp')}</small>}</label>
    <label>{t('form.recurrence')}<select value={e.recurrence_type||'recurring'} onChange={x=>set('recurrence_type',x.target.value)}><option value="recurring">{t('form.recurring')}</option><option value="one_time">{t('form.oneTime')}</option></select></label>
    {e.recurrence_type!=='one_time'?<label>{t('form.billing')}<select value={e.billing_interval} onChange={x=>interval(x.target.value)}><option value="monthly">{t('interval.monthly')}</option><option value="quarterly">{t('interval.quarterly')}</option><option value="halfyearly">{t('interval.halfyearly')}</option><option value="yearly">{t('interval.yearly')}</option><option value="custom">{t('interval.custom')}</option></select></label>:<div/>}
    {e.recurrence_type!=='one_time'&&e.billing_interval==='custom'&&<label>{t('form.everyMonths')}<input type="number" min="1" value={e.interval_months} onChange={x=>set('interval_months',x.target.value)}/></label>}
    <label className="category-field">{t('form.category')}<div className="select-with-action"><select value={e.category_id||''} onChange={x=>set('category_id',x.target.value||null)}><option value="">{t('form.noCategory')}</option>{categoryOptions.map(c=><option key={c.id} value={c.id}>{c.name}{c.scope==='private'?` · ${t('catalog.private')}`:''}</option>)}</select><button type="button" className="inline-add compact-add" title={t('form.addCategory')} onClick={()=>setAddingCategory(v=>!v)}><Plus size={17}/></button></div>{addingCategory&&<div className="inline-create"><input autoFocus value={newCategory} onChange={x=>setNewCategory(x.target.value)} placeholder={t('form.newCategory')} onKeyDown={x=>{if(x.key==='Enter'){x.preventDefault();addCategory()}if(x.key==='Escape'){setAddingCategory(false);setNewCategory('')}}}/><input type="color" value={newColor} onChange={x=>setNewColor(x.target.value)}/><button type="button" disabled={categoryBusy||!newCategory.trim()} onClick={addCategory}>{categoryBusy?'…':t('create')}</button></div>}{categoryError&&<small className="form-error">{categoryError}</small>}</label>
    <label className="category-field">{t('form.account')}<div className="select-with-action"><select value={e.account_id||''} onChange={x=>set('account_id',x.target.value||null)}><option value="">{t('form.noAccount')}</option>{accountOptions.map(a=><option key={a.id} value={a.id}>{a.name}{a.scope==='private'?` · ${t('catalog.private')}`:''}</option>)}</select><button type="button" className="inline-add compact-add" title={t('form.addAccount')} onClick={()=>setAddingAccount(v=>!v)}><Plus size={17}/></button></div>{addingAccount&&<div className="inline-create account-create"><input autoFocus value={newAccount} onChange={x=>setNewAccount(x.target.value)} placeholder={t('form.newAccount')} onKeyDown={x=>{if(x.key==='Enter'){x.preventDefault();addAccount()}if(x.key==='Escape'){setAddingAccount(false);setNewAccount('')}}}/><select value={newAccountKind} onChange={x=>setNewAccountKind(x.target.value)}><option value="bank">{t('accountKind.bank')}</option><option value="credit_card">{t('accountKind.creditCard')}</option><option value="debit_card">{t('accountKind.debitCard')}</option><option value="paypal">PayPal</option><option value="direct_debit">{t('accountKind.directDebit')}</option><option value="cash">{t('accountKind.cash')}</option><option value="other">{t('accountKind.other')}</option></select><button type="button" disabled={accountBusy||!newAccount.trim()} onClick={addAccount}>{accountBusy?'…':t('create')}</button></div>}{accountError&&<small className="form-error">{accountError}</small>}</label>
  </section>

  {priceChanged&&<div className="price-effective-row"><div className="form-warning"><Info size={16}/>{t('form.priceChangedHint')}</div><label>{t('form.priceFrom')}<input type="date" value={e.price_effective_from||today()} onChange={x=>set('price_effective_from',x.target.value||today())}/></label></div>}
  {(activePastEnd||endBeforeDue)&&<div className="form-warning warning"><Info size={16}/><span>{activePastEnd&&t('form.warnPastEnd')}{activePastEnd&&endBeforeDue?' · ':''}{endBeforeDue&&t('form.warnEndBeforeDue')}</span></div>}

  <details className="form-section"><summary><CalendarClock size={17}/><span><strong>{t('form.sectionContract')}</strong><small>{t('form.sectionContractSub')}</small></span><ChevronDown size={16}/></summary><div className="form-grid section-body">
    <label>{t('form.start')}<input type="date" value={e.start_date||''} onChange={x=>set('start_date',x.target.value||null)}/></label>
    <label>{t('form.minTerm')}<input type="number" min="1" value={e.minimum_term_months||''} onChange={x=>set('minimum_term_months',x.target.value||null)}/><small>{t('form.minTermHelp')}</small></label>
    <label>{t('form.end')}<input type="date" value={e.contract_end||''} onChange={x=>set('contract_end',x.target.value||null)}/></label>
    <label>{t('form.nextDue')}<input type="date" value={e.next_due_date||''} onChange={x=>set('next_due_date',x.target.value||null)}/></label>
  </div></details>

  <details className="form-section"><summary><RotateCcw size={17}/><span><strong>{t('form.sectionRenewal')}</strong><small>{t('form.sectionRenewalSub')}</small></span><ChevronDown size={16}/></summary><div className="form-grid section-body">
    <label>{t('form.notice')}<select value={[14,30,60,90].includes(Number(e.cancellation_notice_days))?String(e.cancellation_notice_days):(e.cancellation_notice_days===null||e.cancellation_notice_days===''?'':'custom')} onChange={x=>{const v=x.target.value;set('cancellation_notice_days',v==='custom'?(e.cancellation_notice_days||1):(v===''?null:Number(v)))}}><option value="">{t('form.noticeNone')}</option><option value="14">{t('form.notice14')}</option><option value="30">{t('form.notice30')}</option><option value="60">{t('form.notice60')}</option><option value="90">{t('form.notice90')}</option><option value="custom">{t('form.noticeCustom')}</option></select></label>
    <label>{t('form.cancelBy')}<input type="date" value={e.cancellation_date||''} onChange={x=>set('cancellation_date',x.target.value||null)}/><small>{t('form.cancelHelp')}</small></label>
    {e.cancellation_notice_days!==null&&e.cancellation_notice_days!==''&&![14,30,60,90].includes(Number(e.cancellation_notice_days))&&<label>{t('form.noticeDays')}<input type="number" min="0" value={e.cancellation_notice_days??''} onChange={x=>set('cancellation_notice_days',x.target.value||null)}/></label>}
    <label className="check"><input type="checkbox" checked={e.auto_renew} onChange={x=>setE((p:any)=>({...p,auto_renew:x.target.checked,renewal_period_months:x.target.checked?(p.renewal_period_months||12):p.renewal_period_months}))}/>{t('form.autoRenew')}</label>
    {e.auto_renew&&<><label>{t('form.renewMonths')}<input type="number" min="1" value={e.renewal_period_months||''} onChange={x=>set('renewal_period_months',x.target.value||null)}/></label><label>{t('form.renewAmount')}<input type="number" min="0.01" step="0.01" value={e.renewal_amount||''} onChange={x=>set('renewal_amount',x.target.value||null)}/><small>{t('form.renewAmountHelp')}</small></label></>}
  </div></details>

  <details className="form-section"><summary><Tag size={17}/><span><strong>{t('form.sectionMore')}</strong><small>{t('form.sectionMoreSub')}</small></span><ChevronDown size={16}/></summary><div className="form-grid section-body">
    <label>{t('form.status')}<select value={e.status} onChange={x=>set('status',x.target.value)}><option value="active">{t('form.active')}</option><option value="paused">{t('form.paused')}</option><option value="cancelled">{t('form.cancelled')}</option><option value="ended">{t('form.ended')}</option></select></label>
    <label className="check"><input type="checkbox" checked={e.essential} onChange={x=>set('essential',x.target.checked)}/>{t('form.essential')}</label>
    <label>{t('form.contractReference')}<input value={e.contract_reference||''} onChange={x=>set('contract_reference',x.target.value)}/></label>
    <label>{t('form.contractUrl')}<input type="url" value={e.contract_url||''} onChange={x=>set('contract_url',x.target.value)} placeholder="https://…"/></label>
    <label className="span2">{t('form.tags')}<input value={e.tags} onChange={x=>set('tags',x.target.value)}/></label>
  </div></details>

  <details className="form-section ai-context-section"><summary><BrainCircuit size={17}/><span><strong>{t('form.sectionAi')}</strong><small>{t('form.sectionAiSub')}</small></span><ChevronDown size={16}/></summary><div className="section-body"><label>{t('form.notes')}<textarea rows={4} value={e.notes} onChange={x=>set('notes',x.target.value)} placeholder={t('form.notesPlaceholder')}/><small>{t('form.notesHelp')}</small></label></div></details>

  {expense&&!isClone&&(expense.price_history||[]).length>1&&<details className="form-section compact-section"><summary><WalletCards size={17}/><span><strong>{t('form.priceHistory')}</strong><small>{t('form.priceHistorySub')}</small></span><ChevronDown size={16}/></summary><div className="price-history section-body">{(expense.price_history||[]).map(p=><div key={p.id}><span>{dateFmt(p.valid_from)}{p.valid_to?` – ${dateFmt(p.valid_to)}`:` – ${t('form.continues')}`}</span><b>{money(p.amount,expense.currency)}</b></div>)}{expense.next_price_change&&<small>{t('form.planned',{amount:money(expense.next_price_change.amount,expense.currency),date:dateFmt(expense.next_price_change.valid_from)})}</small>}</div></details>}
  {history.length>0&&<details className="form-section compact-section"><summary><Info size={17}/><span><strong>{t('form.changeHistory')}</strong><small>{history.length}</small></span><ChevronDown size={16}/></summary><div className="change-history section-body">{history.slice(0,12).map(h=><div key={h.id}><strong>{new Intl.DateTimeFormat(undefined,{dateStyle:'short',timeStyle:'short'}).format(new Date(h.created_at))}</strong><span>{h.action}</span><code>{Object.keys(h.changes||{}).join(', ')||'–'}</code></div>)}</div></details>}
  <div className="form-actions"><button type="button" className="secondary" onClick={onCancel}>{t('cancel')}</button><button disabled={busy}>{busy?t('form.saving'):t('form.save')}</button></div>
 </form>
}
