import {createContext,useContext,useMemo,useState,type ReactNode} from 'react';

export type Language='de'|'en';
const strings:Record<Language,Record<string,string>>={
 de:{
  'brand.tagline':'Behalte deine Fixkosten im Blick.','login.setup':'Richte deinen ersten Administrator ein.','login.signin':'Melde dich an, um deine Fixkosten zu verwalten.','login.username':'Benutzername','login.display':'Anzeigename','login.password':'Passwort','login.wait':'Bitte warten …','login.bootstrap':'PenguCost einrichten','login.submit':'Anmelden','login.local':'Deine Daten bleiben in deiner eigenen PenguCost-Instanz.',
  'nav.dashboard':'Übersicht','nav.costs':'Kosten & Verträge','nav.accounts':'Konten & Rubriken','nav.ai':'KI Analyse','nav.users':'Benutzer','nav.settings':'Einstellungen','role.admin':'Administrator','role.user':'Benutzer','logout':'Abmelden','add.expense':'Ausgabe hinzufügen','new.expense':'Neue Ausgabe','edit.expense':'Ausgabe bearbeiten',
  'dashboard.eyebrow':'FIXKOSTEN COCKPIT','dashboard.hero1':'Alles, was regelmäßig Geld kostet.','dashboard.hero2':'Auf einen Blick.','dashboard.heroSub':'Verträge, Abos und laufende Kosten vergleichen, filtern und rechtzeitig handeln.','stat.monthly':'Monatlich','stat.yearly':'Jährlich','stat.contracts':'Verträge','stat.notice':'Kündigung im Blick','stat.selected':'{count} ausgewählte Kosten','stat.perDay':'{value} pro Tag','stat.autoRenew':'{count} mit Auto-Verlängerung','stat.next60':'nächste 60 Tage','chart.development':'Kostenentwicklung','chart.selectionAvg':'Monatlicher Durchschnitt der Auswahl','chart.category':'Nach Rubrik','chart.monthShare':'Anteil am Monatswert','perMonth':'/ Monat',
  'selection.title':'In Auswertung enthalten','selection.help':'Standardmäßig sind alle eigenen aktiven Kosten ausgewählt. Klicke Positionen an, um sie temporär aus allen Kennzahlen und Diagrammen auszublenden.','selection.none':'Alle abwählen','selection.all':'Alle auswählen','dates.title':'Nächste Termine','dates.sub':'Kündigung & Vertragsende','dates.cancelBy':'Kündigen bis','dates.contractEnd':'Vertragsende','dates.empty':'Keine Termine in den nächsten 60 Tagen.',
  'costs.title':'Kosten & Verträge','costs.sub':'Alle laufenden Zahlungen mit Fälligkeiten und Vertragsdaten.','costs.add':'Hinzufügen','costs.search':'Name, Anbieter oder Rubrik suchen …','costs.entries':'{count} Einträge','costs.name':'Name','costs.category':'Rubrik','costs.billing':'Abrechnung','costs.month':'Monat','costs.year':'Jahr','costs.account':'Konto','costs.cancelBy':'Kündigen bis','costs.noCategory':'Ohne Kategorie','costs.cancelled':'Gekündigt am {date}','costs.term':'{count} Mon. Laufzeit','costs.until':'bis {date}','costs.empty':'Noch keine passenden Ausgaben vorhanden.','clone':'Klonen','edit':'Bearbeiten','delete':'Löschen','confirm.delete':'„{name}“ wirklich löschen?','copySuffix':'Kopie',
  'interval.monthly':'Monatlich','interval.quarterly':'Vierteljährlich','interval.halfyearly':'Halbjährlich','interval.yearly':'Jährlich','interval.custom':'Individuell','interval.months':'{count} Monate',
  'accounts.title':'Konten & Rubriken','accounts.adminSub':'Globale Vorlagen für alle Benutzer verwalten.','accounts.userSub':'Vom Administrator bereitgestellte Konten und Rubriken. Ausblenden wirkt nur auf deine Ansicht.','accounts.restore':'Ausgeblendete wiederherstellen','accounts.deleted':'Gelöscht.','accounts.hidden':'Nur für dich ausgeblendet.','accounts.restored':'{count} ausgeblendete Einträge wiederhergestellt.','accounts.confirmGlobal':'„{name}“ wirklich global löschen?','accounts.payments':'Konten & Zahlungswege','accounts.paymentsSub':'Girokonto, Kreditkarte, PayPal oder Gemeinschaftskonto.','accounts.new':'Neues globales Konto','categories.title':'Rubriken','categories.sub':'Versicherungen, Energie, Abos und weitere Kostengruppen.','categories.new':'Neue globale Rubrik','global.delete':'Global löschen','hide.mine':'Nur für mich ausblenden',
  'ai.title':'KI Analyse','ai.sub':'Analysiert ausschließlich deine eigenen ausgewählten Kosten.','ai.optimize':'Was möchtest du optimieren?','ai.profile':'KI-Profil','ai.noneProfile':'Kein Profil verfügbar','ai.positions':'{count} Kostenpositionen','ai.analyze':'Kosten analysieren','ai.analyzing':'Analysiere …','ai.userInfo':'Benutzer können nur vom Administrator freigegebene KI-Profile auswählen. API-Keys und Endpunkte werden hier nicht angezeigt.','ai.adminMissing':'Lege zuerst unter Einstellungen ein KI-Profil an.','ai.userMissing':'Der Administrator hat noch kein KI-Profil freigegeben.','ai.resultSub':'Konkrete Hinweise statt pauschaler Spar-Tipps.','ai.none':'Noch keine Analyse','ai.example':'Beispiel: „Ich will 80 € pro Monat sparen. Wo ist es realistisch?“','ai.error':'Analyse nicht verfügbar: {message}','ai.checkProfile':' – prüfe das KI-Profil in den Einstellungen.','ai.selectHelp':'Standardmäßig sind alle deine aktiven Kosten ausgewählt. Du kannst sie für diese Analyse abwählen.','ai.promptSaved':'Analyse-Prompt wird in deinem Benutzerprofil gespeichert und mit deinem Export gesichert.',
  'users.title':'Benutzer','users.sub':'Lokale Benutzer und Rollen. Kosten- und Vertragsdaten anderer Benutzer sind im normalen Admin-Bereich nicht einsehbar.','users.add':'Benutzer','users.modal':'Benutzer hinzufügen','users.initialPassword':'Initiales Passwort','create':'Erstellen','cancel':'Abbrechen',
  'settings.title':'Einstellungen','settings.subAdmin':'Darstellung, Sprache, persönliche Erinnerungen, globale Kategorien, Datenexport und KI-Profile.','settings.subUser':'Darstellung, Sprache, persönliche Erinnerungen und Datenexport.','settings.appearance':'Darstellung','settings.appearanceSub':'Theme wird lokal im Browser gespeichert und ohne sichtbaren Farbwechsel beim Seitenaufruf geladen.','settings.language':'Sprache','settings.languageSub':'Die Sprache wird pro Benutzer gespeichert.','settings.german':'Deutsch','settings.english':'English','settings.categoryColors':'Kategoriefarben','settings.categoryColorsSub':'Globale Farben für Übersicht, Diagramme und Kostenlisten aller Benutzer.','settings.categoryColorsOnly':'Nur Administratoren ändern globale Rubrikfarben.','settings.saved':'Gespeichert','settings.saving':'Speichere …','settings.reminders':'Kündigungs-Erinnerungen','settings.remindersSub':'Dein persönlicher Vorlauf für die Glocke oben rechts.','settings.days':'Tage vor Kündigungsfrist','settings.daysHelp':'Beispiel: 30 bedeutet, dass PenguCost 30 Tage vor „Kündigen bis“ erinnert.','settings.reminderHint':'Diese Einstellung gilt nur für deinen Benutzer. Verträge mit automatischer Verlängerung werden besonders markiert.','save':'Speichern',
  'settings.data':'Export & Import','settings.dataSub':'JSON-Sicherungen für persönliche Daten oder – als Admin – für die komplette Instanz.','settings.userExport':'Meine Daten exportieren','settings.userImport':'Meine Daten importieren','settings.userExportHelp':'Enthält deine Kosten/Verträge, Preisverläufe, ausgeblendete Konten/Rubriken, Erinnerungen, Theme, Sprache und deinen KI-Prompt.','settings.userImportWarn':'Beim Import werden deine bisherigen privaten PenguCost-Daten durch den Inhalt der JSON-Datei ersetzt. Globale Vorlagen und andere Benutzer bleiben unverändert.','settings.adminExport':'Komplett-Export (Admin)','settings.adminImport':'Komplett-Import (Admin)','settings.adminExportHelp':'Enthält alle Benutzer, alle Kosten/Verträge, globale Kataloge, Einstellungen und KI-Profile inklusive API-Keys. Die JSON-Datei vertraulich behandeln.','settings.adminImportWarn':'Der Komplett-Import ersetzt die gesamte PenguCost-Datenbank. Nur für Wiederherstellung/Migration verwenden.','settings.importOk':'Import abgeschlossen: {count} Kostenpositionen.','settings.importFullOk':'Komplett-Import abgeschlossen.','settings.invalidJson':'Ungültige JSON-Datei.','settings.confirmUserImport':'Deine aktuellen privaten Daten wirklich durch diesen Export ersetzen?','settings.confirmAdminImport':'ACHTUNG: Die komplette PenguCost-Datenbank wird ersetzt. Fortfahren?',
  'settings.aiTitle':'KI-Anbieter & Modelle','settings.aiSub':'Nur Administratoren verwalten Endpunkte, Modelle und API-Keys. Benutzer sehen ausschließlich freigegebene Profile.','settings.aiNo':'Noch kein KI-Profil angelegt.','settings.aiEdit':'KI-Profil bearbeiten','settings.aiNew':'Neues KI-Profil','settings.aiName':'Name','settings.aiProvider':'Anbieter','settings.aiBase':'Base URL','settings.aiModel':'Modell','settings.aiKey':'API Key','settings.aiExpose':'Für Benutzer freigeben','settings.aiAdd':'Profil hinzufügen','settings.aiSave':'Änderungen speichern','settings.aiActive':'Aktiv','settings.aiInactive':'Inaktiv','settings.aiKeySet':'API-Key hinterlegt','settings.aiNoKey':'ohne API-Key','settings.aiEndpointDefault':'Standard-Endpunkt','settings.aiKeyKeep':'Gespeichert – leer lassen zum Behalten','settings.aiKeyOptional':'API Key / bei Ollama optional','settings.aiFoot':'Claude nutzt die native Anthropic Messages API. Ollama, OpenAI, Grok/xAI, Gemini, IONOS und Custom werden über OpenAI-kompatible Chat-Completions angesprochen.','settings.aiUserTitle':'KI','settings.aiUserSub':'KI-Anbieter, API-Keys und Modelle werden ausschließlich vom Administrator verwaltet.','settings.aiUserHint':'Unter „KI Analyse“ kannst du aus allen vom Administrator freigegebenen Profilen wählen und deine eigenen Kosten analysieren.',
  'reminders.title':'Erinnerungen · {count}','reminders.kindDue':'Kündigungsfrist läuft','reminders.kindRisk':'Verlängerung droht','reminders.kindRenewed':'Automatisch verlängert','reminders.attentionOne':'1 Vertrag braucht Aufmerksamkeit','reminders.attentionMany':'{count} Verträge brauchen Aufmerksamkeit','reminders.ok':'Alles im grünen Bereich','reminders.lead':'Vorlauf: {count} Tage vor dem Kündigungsstichtag.','reminders.today':'Heute letzter Kündigungstag','reminders.daysLeft':'Noch {count} Tage bis zum Kündigungsstichtag','reminders.renewed':'Dieser Vertrag befindet sich bereits in einer automatischen Verlängerungsperiode{period}.','reminders.done':'Erledigt','reminders.later':'Später erinnern','reminders.cancelled':'Vertrag gekündigt','reminders.confirm':'Kündigung bestätigen','reminders.day':'1 Tag','reminders.days3':'3 Tage','reminders.days7':'7 Tage','reminders.days14':'14 Tage','reminders.days30':'30 Tage','reminders.none':'Keine anstehenden Erinnerungen','reminders.noneSub':'PenguCost meldet sich, sobald ein Vertrag in deinen eingestellten Erinnerungszeitraum fällt.','reminders.cancelBy':'Kündigen bis {date}','reminders.end':'Vertragsende {date}',
  'form.name':'Name','form.provider':'Anbieter','form.amount':'Betrag (€)','form.priceFrom':'Neuer Preis gültig ab','form.priceHelp':'Nur relevant, wenn du den Betrag änderst. Alte Zeiträume bleiben unverändert.','form.priceHistory':'Preisverlauf','form.continues':'weiter','form.planned':'Geplant: {amount} ab {date}','form.billing':'Abrechnung','form.everyMonths':'Alle X Monate','form.category':'Kategorie','form.noCategory':'Ohne Kategorie','form.hidden':'ausgeblendet','form.account':'Konto / Zahlungsweg','form.noAccount':'Nicht zugeordnet','form.start':'Vertragsbeginn','form.minTerm':'Mindestlaufzeit (Monate)','form.minTermHelp':'Wenn kein Vertragsende gesetzt ist, wird es daraus berechnet.','form.end':'Vertragsende','form.endHelp':'Darf unterjährig liegen und hat Vorrang vor der Mindestlaufzeit.','form.nextDue':'Nächste Fälligkeit','form.cancelBy':'Kündigen bis','form.cancelHelp':'Kann leer bleiben, wenn Vertragsende und Kündigungsfrist gesetzt sind.','form.notice':'Kündigungsfrist','form.noticeNone':'Keine / unbekannt','form.notice14':'14 Tage','form.notice30':'1 Monat / 30 Tage','form.notice60':'2 Monate / 60 Tage','form.notice90':'3 Monate / 90 Tage','form.noticeCustom':'Individuell','form.noticeDays':'Kündigungsfrist individuell (Tage)','form.status':'Status','form.active':'Aktiv','form.paused':'Pausiert','form.cancelled':'Gekündigt','form.ended':'Beendet','form.autoRenew':'Automatische Verlängerung','form.renewMonths':'Verlängerung um (Monate)','form.essential':'Essenziell / kaum einsparbar','form.tags':'Tags','form.notes':'Notizen (für KI-Analyse)','form.notesHelp':'Beschreibe Zweck, Vorteile oder Einschränkungen dieser Ausgabe. Diese Information wird bei deiner KI-Analyse berücksichtigt.','form.save':'Speichern','form.saving':'Speichern …',
  'contract':'Vertrag','version':'Version {version}'
 },
 en:{
  'brand.tagline':'Know your fixed costs.','login.setup':'Set up your first administrator.','login.signin':'Sign in to manage your fixed costs.','login.username':'Username','login.display':'Display name','login.password':'Password','login.wait':'Please wait …','login.bootstrap':'Set up PenguCost','login.submit':'Sign in','login.local':'Your data stays inside your own PenguCost instance.',
  'nav.dashboard':'Overview','nav.costs':'Costs & Contracts','nav.accounts':'Accounts & Categories','nav.ai':'AI Analysis','nav.users':'Users','nav.settings':'Settings','role.admin':'Administrator','role.user':'User','logout':'Sign out','add.expense':'Add expense','new.expense':'New expense','edit.expense':'Edit expense',
  'dashboard.eyebrow':'FIXED COST COCKPIT','dashboard.hero1':'Everything that costs money regularly.','dashboard.hero2':'At a glance.','dashboard.heroSub':'Compare contracts, subscriptions and recurring costs, filter them and act in time.','stat.monthly':'Monthly','stat.yearly':'Yearly','stat.contracts':'Contracts','stat.notice':'Cancellation watch','stat.selected':'{count} selected costs','stat.perDay':'{value} per day','stat.autoRenew':'{count} with auto-renewal','stat.next60':'next 60 days','chart.development':'Cost development','chart.selectionAvg':'Monthly average of the selection','chart.category':'By category','chart.monthShare':'Share of monthly value','perMonth':'/ month',
  'selection.title':'Included in analysis','selection.help':'All of your active costs are selected by default. Click items to temporarily exclude them from all metrics and charts.','selection.none':'Deselect all','selection.all':'Select all','dates.title':'Upcoming dates','dates.sub':'Cancellation & contract end','dates.cancelBy':'Cancel by','dates.contractEnd':'Contract end','dates.empty':'No dates in the next 60 days.',
  'costs.title':'Costs & Contracts','costs.sub':'All recurring payments with due dates and contract details.','costs.add':'Add','costs.search':'Search name, provider or category …','costs.entries':'{count} entries','costs.name':'Name','costs.category':'Category','costs.billing':'Billing','costs.month':'Month','costs.year':'Year','costs.account':'Account','costs.cancelBy':'Cancel by','costs.noCategory':'No category','costs.cancelled':'Cancelled on {date}','costs.term':'{count} mo. term','costs.until':'until {date}','costs.empty':'No matching expenses yet.','clone':'Clone','edit':'Edit','delete':'Delete','confirm.delete':'Really delete “{name}”?','copySuffix':'Copy',
  'interval.monthly':'Monthly','interval.quarterly':'Quarterly','interval.halfyearly':'Half-yearly','interval.yearly':'Yearly','interval.custom':'Custom','interval.months':'{count} months',
  'accounts.title':'Accounts & Categories','accounts.adminSub':'Manage global templates for all users.','accounts.userSub':'Accounts and categories provided by the administrator. Hiding only affects your view.','accounts.restore':'Restore hidden items','accounts.deleted':'Deleted.','accounts.hidden':'Hidden only for you.','accounts.restored':'Restored {count} hidden items.','accounts.confirmGlobal':'Really delete “{name}” globally?','accounts.payments':'Accounts & payment methods','accounts.paymentsSub':'Current account, credit card, PayPal or shared account.','accounts.new':'New global account','categories.title':'Categories','categories.sub':'Insurance, energy, subscriptions and other cost groups.','categories.new':'New global category','global.delete':'Delete globally','hide.mine':'Hide only for me',
  'ai.title':'AI Analysis','ai.sub':'Analyzes only your own selected costs.','ai.optimize':'What would you like to optimize?','ai.profile':'AI profile','ai.noneProfile':'No profile available','ai.positions':'{count} cost items','ai.analyze':'Analyze costs','ai.analyzing':'Analyzing …','ai.userInfo':'Users can only select AI profiles enabled by the administrator. API keys and endpoints are not shown here.','ai.adminMissing':'Create an AI profile in Settings first.','ai.userMissing':'The administrator has not enabled an AI profile yet.','ai.resultSub':'Concrete suggestions instead of generic saving tips.','ai.none':'No analysis yet','ai.example':'Example: “I want to save €80 per month. Where is that realistic?”','ai.error':'Analysis unavailable: {message}','ai.checkProfile':' – check the AI profile in Settings.','ai.selectHelp':'All of your active costs are selected by default. You can deselect them for this analysis.','ai.promptSaved':'Your analysis prompt is stored in your user profile and included in your export.',
  'users.title':'Users','users.sub':'Local users and roles. Other users’ cost and contract data is not visible in the normal admin area.','users.add':'User','users.modal':'Add user','users.initialPassword':'Initial password','create':'Create','cancel':'Cancel',
  'settings.title':'Settings','settings.subAdmin':'Appearance, language, personal reminders, global categories, data export and AI profiles.','settings.subUser':'Appearance, language, personal reminders and data export.','settings.appearance':'Appearance','settings.appearanceSub':'The theme is stored locally in the browser and applied without a visible color flash.','settings.language':'Language','settings.languageSub':'Language is stored per user.','settings.german':'Deutsch','settings.english':'English','settings.categoryColors':'Category colors','settings.categoryColorsSub':'Global colors for overview, charts and cost lists of all users.','settings.categoryColorsOnly':'Only administrators can change global category colors.','settings.saved':'Saved','settings.saving':'Saving …','settings.reminders':'Cancellation reminders','settings.remindersSub':'Your personal lead time for the bell in the top bar.','settings.days':'Days before cancellation deadline','settings.daysHelp':'Example: 30 means PenguCost reminds you 30 days before “Cancel by”.','settings.reminderHint':'This setting only applies to your user. Contracts with automatic renewal are highlighted.','save':'Save',
  'settings.data':'Export & Import','settings.dataSub':'JSON backups for personal data or – as admin – the complete instance.','settings.userExport':'Export my data','settings.userImport':'Import my data','settings.userExportHelp':'Includes your costs/contracts, price history, hidden accounts/categories, reminders, theme, language and AI prompt.','settings.userImportWarn':'Importing replaces your current private PenguCost data with the JSON content. Global templates and other users remain untouched.','settings.adminExport':'Full export (Admin)','settings.adminImport':'Full import (Admin)','settings.adminExportHelp':'Includes all users, all costs/contracts, global catalogs, settings and AI profiles including API keys. Treat the JSON file as confidential.','settings.adminImportWarn':'Full import replaces the entire PenguCost database. Use only for restore/migration.','settings.importOk':'Import completed: {count} cost items.','settings.importFullOk':'Full import completed.','settings.invalidJson':'Invalid JSON file.','settings.confirmUserImport':'Really replace your current private data with this export?','settings.confirmAdminImport':'WARNING: The complete PenguCost database will be replaced. Continue?',
  'settings.aiTitle':'AI providers & models','settings.aiSub':'Only administrators manage endpoints, models and API keys. Users only see enabled profiles.','settings.aiNo':'No AI profile created yet.','settings.aiEdit':'Edit AI profile','settings.aiNew':'New AI profile','settings.aiName':'Name','settings.aiProvider':'Provider','settings.aiBase':'Base URL','settings.aiModel':'Model','settings.aiKey':'API key','settings.aiExpose':'Enable for users','settings.aiAdd':'Add profile','settings.aiSave':'Save changes','settings.aiActive':'Active','settings.aiInactive':'Inactive','settings.aiKeySet':'API key stored','settings.aiNoKey':'no API key','settings.aiEndpointDefault':'Default endpoint','settings.aiKeyKeep':'Stored – leave empty to keep','settings.aiKeyOptional':'API key / optional for Ollama','settings.aiFoot':'Claude uses the native Anthropic Messages API. Ollama, OpenAI, Grok/xAI, Gemini, IONOS and Custom use OpenAI-compatible chat completions.','settings.aiUserTitle':'AI','settings.aiUserSub':'AI providers, API keys and models are managed exclusively by the administrator.','settings.aiUserHint':'Under “AI Analysis” you can select any profile enabled by the administrator and analyze your own costs.',
  'reminders.title':'Reminders · {count}','reminders.kindDue':'Cancellation window','reminders.kindRisk':'Renewal at risk','reminders.kindRenewed':'Automatically renewed','reminders.attentionOne':'1 contract needs attention','reminders.attentionMany':'{count} contracts need attention','reminders.ok':'All clear','reminders.lead':'Lead time: {count} days before the cancellation deadline.','reminders.today':'Today is the final cancellation day','reminders.daysLeft':'{count} days until the cancellation deadline','reminders.renewed':'This contract is already in an automatic renewal period{period}.','reminders.done':'Done','reminders.later':'Remind later','reminders.cancelled':'Contract cancelled','reminders.confirm':'Confirm cancellation','reminders.day':'1 day','reminders.days3':'3 days','reminders.days7':'7 days','reminders.days14':'14 days','reminders.days30':'30 days','reminders.none':'No upcoming reminders','reminders.noneSub':'PenguCost will notify you when a contract enters your reminder window.','reminders.cancelBy':'Cancel by {date}','reminders.end':'Contract end {date}',
  'form.name':'Name','form.provider':'Provider','form.amount':'Amount (€)','form.priceFrom':'New price valid from','form.priceHelp':'Only relevant when changing the amount. Past periods stay unchanged.','form.priceHistory':'Price history','form.continues':'ongoing','form.planned':'Planned: {amount} from {date}','form.billing':'Billing','form.everyMonths':'Every X months','form.category':'Category','form.noCategory':'No category','form.hidden':'hidden','form.account':'Account / payment method','form.noAccount':'Not assigned','form.start':'Contract start','form.minTerm':'Minimum term (months)','form.minTermHelp':'If no contract end is set, it is calculated from this value.','form.end':'Contract end','form.endHelp':'May be during the year and overrides the minimum term.','form.nextDue':'Next due date','form.cancelBy':'Cancel by','form.cancelHelp':'May stay empty if contract end and cancellation notice are set.','form.notice':'Cancellation notice','form.noticeNone':'None / unknown','form.notice14':'14 days','form.notice30':'1 month / 30 days','form.notice60':'2 months / 60 days','form.notice90':'3 months / 90 days','form.noticeCustom':'Custom','form.noticeDays':'Custom cancellation notice (days)','form.status':'Status','form.active':'Active','form.paused':'Paused','form.cancelled':'Cancelled','form.ended':'Ended','form.autoRenew':'Automatic renewal','form.renewMonths':'Renewal period (months)','form.essential':'Essential / difficult to save','form.tags':'Tags','form.notes':'Notes (for AI analysis)','form.notesHelp':'Describe the purpose, benefits or constraints of this expense. This information is considered in your AI analysis.','form.save':'Save','form.saving':'Saving …',
  'contract':'Contract','version':'Version {version}'
 }
};

type Ctx={language:Language;setLanguage:(x:Language)=>void;t:(key:string,vars?:Record<string,string|number>)=>string};
const I18nContext=createContext<Ctx|null>(null);

export function I18nProvider({children}:{children:ReactNode}){
 const initial:Language=(localStorage.getItem('pengucost-language')==='en'||(!localStorage.getItem('pengucost-language')&&navigator.language.toLowerCase().startsWith('en')))?'en':'de';
 const[language,setState]=useState<Language>(initial);
 const setLanguage=(x:Language)=>{localStorage.setItem('pengucost-language',x);document.documentElement.lang=x;setState(x)};
 const value=useMemo<Ctx>(()=>({language,setLanguage,t:(key:string,vars?:Record<string,string|number>)=>{let out=strings[language][key]??strings.de[key]??key;for(const[k,v]of Object.entries(vars||{}))out=out.replaceAll(`{${k}}`,String(v));return out}}),[language]);
 document.documentElement.lang=language;
 return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>
}

export function useI18n(){const v=useContext(I18nContext);if(!v)throw new Error('I18nProvider missing');return v}
export const localeFor=(language:Language)=>language==='en'?'en-GB':'de-DE';
