import type {Expense} from './api';
export const dayKey=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
export const asDate=(s:string)=>new Date(s+'T12:00:00');
export function stateAt(x:Expense,d:Date):Expense{const k=dayKey(d);const phases=[...(x.contract_versions||[])].sort((a,b)=>a.effective_from.localeCompare(b.effective_from));const v=phases.filter(v=>v.effective_from<=k).at(-1)||phases[0];return v?{...x,...v.values}:x}
export function contractEnd(x:Expense,d:Date){x=stateAt(x,d);if(!x.contract_end)return null;const original=asDate(x.contract_end);let end=original;if(x.auto_renew&&!x.cancelled_on&&x.status==='active'&&x.renewal_period_months){let n=0;while(end<d&&n<1200){n++;const next=new Date(original.getFullYear(),original.getMonth()+n*x.renewal_period_months,1,12);next.setDate(Math.min(original.getDate(),new Date(next.getFullYear(),next.getMonth()+1,0).getDate()));end=next}}return end}
export function historicalActive(x:Expense,d:Date){const s=stateAt(x,d),k=dayKey(d);const first=x.contract_versions?.[0]?.effective_from||[x.start_date,...(x.price_history||[]).map(p=>p.valid_from)].filter(Boolean).sort()[0];if((first&&k<first)||(x.history_from&&k<x.history_from)||(s.start_date&&k<s.start_date)||['paused','ended'].includes(s.status))return false;if(x.is_archived&&(!x.archived_on||k>x.archived_on))return false;if(s.recurrence_type==='one_time')return k===(s.next_due_date||s.start_date);const end=contractEnd(x,d);return !end||d<=end}
export function amountAt(x:Expense,d:Date){const s=stateAt(x,d),k=dayKey(d);const prices=[...(x.price_history||[])].sort((a,b)=>a.valid_from.localeCompare(b.valid_from));const p=prices.filter(p=>p.valid_from<=k).at(-1)||prices[0];let value=p?.amount??s.amount;if(s.auto_renew&&s.renewal_period_months&&!s.cancelled_on&&s.status==='active'&&s.contract_end&&k>s.contract_end&&s.renewal_amount&&(!p||p.valid_from<=s.contract_end))value=s.renewal_amount;return value}
export function dailyCost(x:Expense,d:Date){if(!historicalActive(x,d))return 0;const s=stateAt(x,d);return s.recurrence_type==='one_time'?amountAt(x,d):amountAt(x,d)/Math.max(1,s.interval_months||1)/new Date(d.getFullYear(),d.getMonth()+1,0).getDate()}
export function monthCost(x:Expense,d:Date,type?:string){let total=0;for(let day=1;day<=new Date(d.getFullYear(),d.getMonth()+1,0).getDate();day++){const when=new Date(d.getFullYear(),d.getMonth(),day,12);if(!type||stateAt(x,when).entry_type===type)total+=dailyCost(x,when)}return total}
